config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :pages
  end

  root 'home#index'
end

app/models/h1_tag.rb
class H1Tag < ActiveRecord::Base
  belongs_to :page
end

app/models/h2_tag.rb
class H2Tag < ActiveRecord::Base
  belongs_to :page
end

app/models/h3_tag.rb
class H3Tag < ActiveRecord::Base
  belongs_to :page
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :h1_tags, dependent: :destroy
  has_many :h2_tags, dependent: :destroy
  has_many :h3_tags, dependent: :destroy
  has_many :url_tags, dependent: :destroy
end

app/models/url_tag.rb
class UrlTag < ActiveRecord::Base
  belongs_to :page
end

app/controllers/api/pages_controller.rb
require 'open-uri'

class Api::PagesController < ApplicationController
  def create
    tmp = Nokogiri::HTML(open(params[:url]))
    @page = Page.create(path: params[:url])

    tmp.css('h1').each do |h1| 
      H1Tag.create(content: h1.text, page_id: @page.id)
    end
    
    tmp.css('h2').each do |h2|
      H2Tag.create(content: h2.text, page_id: @page.id)
    end

    tmp.css('h3').each do |h3|
      H3Tag.create(content: h3.text, page_id: @page.id)
    end

    tmp.css('a').each do |a|
      UrlTag.create(content: a.attr('href'), page_id: @page.id)
    end

    if @page.save
      redirect_to api_page_path(@page)
    else
      redirect_to root_path, notice: "Bad url!"
    end
  end

  def show
    @page = Page.find(params[:id])

    render json: {"h1_tags": @page.h1_tags.map(&:content),
                  "h2_tags": @page.h2_tags.map(&:content),
                  "h3_tags": @page.h3_tags.map(&:content),
                  "url_tags": @page.url_tags.map(&:content)}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>LIM_API</h1>

<%= form_tag api_pages_path, method: :post do %>
  <%= label_tag "Url", nil %>
  <%= text_field_tag "url", nil, required: true, autofocus: true, 
                      pattern: '(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?' %>
  <%= button_tag "Show Content", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LimApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>